title: 咸湖的盐鱼
tagline: Soaked in brackish brine.
description: 一条在盐滩上弹跳的咸鱼留下的痕迹。
url: https://soaked.in
baseurl: /
lang: zh-CN
timezone: Asia/Shanghai

permalink: /:year/:month/:title/

sass:
  style: compressed

include:
  - /_pages

exclude:
  - /README.md


plugins:
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-sitemap

pagination:
  enabled: true
  permalink: /page/:num/
  sort_reverse: true
  per_page: 8
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  tags:
    layouts:
      - 'autopage_tags.html'
    title: ':tag 标签'
    permalink: '/tag/:tag'
    slugify:
      mode: 'default'
      case: false
  categories:
    enabled: false
  collections:
    enabled: false

jekyll-archives:
  enabled: ['year', 'categories']
  layouts:
    year: archive_year
    categories: archive
  permalinks:
    year: '/:year/'
    category: '/category/:name/'
