name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  github-pages:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: vendor/bundle
          key: >-
            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: >-
            ${{ runner.os }}-gems-
      - uses: joshlarsen/jekyll4-deploy-gh-pages@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
